ALTER TABLE "PengirimanProduct"
ADD COLUMN IF NOT EXISTS "hargaVendorTransportir" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "totalHargaVendorTransportir" DOUBLE PRECISION NOT NULL DEFAULT 0;
